# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DeployTo_gh-pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 20
        
    - name: Prepare
      run: |
       cd src
       npm install
       npm run build
       npm run test
       cd dist
       npm link
       cd ..
       cd ..
       npm install -g @angular/cli
       ng new your-angular-project --defaults
       cd your-angular-project
       npm link angular-cli-ghpages
       ng add angular-cli-ghpages

    - name: Deploy
      run: |
       cd your-angular-project
       ng deploy --name="The Buildbot" --email="buildbot@angular2buch.de" --cname=angular-cli-ghpages.angular.schule

    - name: Copy dist folder content to remote
    - run: npx angular-cli-ghpages --dir=dist/browser
