name: Build and Deploy Script

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Set Git Identity
        run: |
          git config user.name "Mohammad Awad"
          git config user.email "Mohammad.omar.awad@gmail.com"

      - name: Get last commit message
        id: vars
        run: echo "LAST_COMMIT=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/browser --message "${{ env.LAST_COMMIT }}"
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
